"""initial schema

Revision ID: 198fa9815fce
Revises: 
Create Date: 2026-06-24 13:00:23.788718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198fa9815fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleeper_player_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('nfl_team', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeper_player_id')
    )
    op.create_table('player_stat_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleeper_player_id', sa.String(length=50), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeper_player_id', 'season', 'week', name='uq_player_stat_cache')
    )
    op.create_table('scoring_ruleset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'LEAGUE_ADMIN', name='account_role'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owner_sleeper_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sleeper_user_id', sa.String(length=50), nullable=False),
    sa.Column('sleeper_display_name', sa.String(length=100), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeper_user_id', 'season', name='uq_sleeper_link_user_season')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'REGULAR', 'PLAYOFFS', 'COMPLETE', name='season_status'), nullable=False),
    sa.Column('scoring_ruleset_id', sa.Integer(), nullable=True),
    sa.Column('playoff_field_per_league', sa.Integer(), nullable=False),
    sa.Column('nfl_playoff_weeks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scoring_ruleset_id'], ['scoring_ruleset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETE', name='bracket_status'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('sleeper_league_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('commish_sleeper_id', sa.String(length=50), nullable=True),
    sa.Column('scoring_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'sleeper_league_id', name='uq_league_season_sleeper')
    )
    op.create_table('league_admin_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'league_id', name='uq_league_admin_grant')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('sleeper_roster_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sleeper_user_id', sa.String(length=50), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('points_against', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('league_finish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sleeper_roster_id', name='uq_team_league_roster')
    )
    op.create_table('bracket_matchup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('nfl_week', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=True),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('team_a_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('team_b_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('bye', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_a_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracket_seed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('qualified_via', sa.Enum('AUTO', 'WILDCARD', name='qualified_via'), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket_id', 'seed', name='uq_bracket_seed_position'),
    sa.UniqueConstraint('bracket_id', 'team_id', name='uq_bracket_seed_team')
    )
    op.create_table('weekly_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('sleeper_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recomputed_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bench_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mismatch_flag', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'week', name='uq_weekly_score_team_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_score')
    op.drop_table('bracket_seed')
    op.drop_table('bracket_matchup')
    op.drop_table('team')
    op.drop_table('league_admin_grant')
    op.drop_table('league')
    op.drop_table('bracket')
    op.drop_table('season')
    op.drop_table('owner_sleeper_link')
    op.drop_table('account')
    op.drop_table('scoring_ruleset')
    op.drop_table('player_stat_cache')
    op.drop_table('player')
    op.drop_table('owner')
    # Drop PostgreSQL ENUM types not removed by drop_table
    sa.Enum(name='qualified_via').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='bracket_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='season_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='account_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
